# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Name (Uzbek)')),
                ('name_uz_uz', models.CharField(max_length=255, null=True, verbose_name='Name (Uzbek)')),
                ('name_uz_ru', models.CharField(max_length=255, null=True, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name (Russian)')),
                ('name_ru_uz', models.CharField(max_length=255, null=True, verbose_name='Name (Russian)')),
                ('name_ru_ru', models.CharField(max_length=255, null=True, verbose_name='Name (Russian)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description_uz', models.TextField(verbose_name='Description (Uzbek)')),
                ('description_uz_uz', models.TextField(null=True, verbose_name='Description (Uzbek)')),
                ('description_uz_ru', models.TextField(null=True, verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_ru_uz', models.TextField(null=True, verbose_name='Description (Russian)')),
                ('description_ru_ru', models.TextField(null=True, verbose_name='Description (Russian)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published At')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.ad', verbose_name='Advertisement')),
            ],
            options={
                'verbose_name': 'Ad Photo',
                'verbose_name_plural': 'Ad Photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='store.ad', verbose_name='Advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ad View',
                'verbose_name_plural': 'Ad Views',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Name (Uzbek)')),
                ('name_uz_uz', models.CharField(max_length=255, null=True, verbose_name='Name (Uzbek)')),
                ('name_uz_ru', models.CharField(max_length=255, null=True, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name (Russian)')),
                ('name_ru_uz', models.CharField(max_length=255, null=True, verbose_name='Name (Russian)')),
                ('name_ru_ru', models.CharField(max_length=255, null=True, verbose_name='Name (Russian)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AdLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.ad', verbose_name='Advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_ads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ad Like',
                'verbose_name_plural': 'Ad Likes',
                'unique_together': {('user', 'ad')},
            },
        ),
    ]
