# Generated by Django 5.2.5 on 2025-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
